=== pypi-data/pypi-mirror-45/packages/opentrons/opentrons-3.8.3-py2.py3-none-any.whl/opentrons/shared_data/labware-json-schema/labwareSchemaV2.json
{
  "$id": "opentronsLabwareSchemaV2",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    }
  },
  "type": "object",
  "additionalProperties": false,
  "required": [
    "otId",
    "deprecated",
    "metadata",
    "brand",
    "parameters",
    "cornerOffsetFromSlot",
    "ordering",
    "dimensions",
    "wells"
  ],
  "properties": {
    "otId": {
      "description": "Unique internal ID generated using UUID",
      "type": "string"
    },
    "deprecated": {
      "description": "Flag specifying whether a labware is deprecated or not",
      "type": "boolean"
    },
    "metadata": {
      "type": "object",
      "description": "Properties used for search and display",
      "additionalProperties": false,
      "required": ["displayName", "displayCategory", "displayVolumeUnits"],
      "properties": {
        "displayName": {
          "description": "Easy to remember name of labware",
          "type": "string"
        },
        "displayCategory": {
          "description": "Label used in UI to categorize labware",
          "type": "string",
          "enum": [
            "tipRack",
            "tubeRack",
            "trough",
            "trash",
            "wellPlate",
            "other"
          ]
        },
        "displayVolumeUnits": {
          "description": "Volume units for display",
          "type": "string",
          "enum": ["ÂµL", "mL", "L"]
        },
        "tags": {
          "type": "array",
          "description": "List of descriptions for a given labware",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "brand": {
      "type": "object",
      "description": "Also for searchability, so that users know exactly which labware this was modeled off",
      "additionalProperties": false,
      "required": ["brand"],
      "properties": {
        "brandId": {
          "type": "array",
          "description": "An array of manufacture numbers pertaining to a given labware",
          "items": {
            "type": "string"
          }
        },
        "brand": {
          "type": "string"
        }
      }
    },
    "parameters": {
      "type": "object",
      "description": "Internal describers used to determine pipette movement to labware",
      "additionalProperties": false,
      "required": [
        "format",
        "isTiprack",
        "loadName",
        "isMagneticModuleCompatible"
      ],
      "properties": {
        "format": {
          "description": "Property to determine compatibility with multichannel pipette",
          "type": "string",
          "enum": ["96Standard", "384Standard", "trough", "irregular", "trash"]
        },
        "quirks": {
          "description": "Property to classify a specific behavior this labware should have",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "isTiprack": {
          "description": "Flag marking whether a labware is a tiprack or not",
          "type": "boolean"
        },
        "tipLength": {
          "description": "Required if labware is tiprack, specifies length of tip from drawing or as measured with calipers",
          "$ref": "#/definitions/positiveNumber"
        },
        "tipOverlap": {
          "description": "Required if labware is tiprack, specifies the length of the area of the tip that overlaps the nozzle of the pipette",
          "$ref": "#/definitions/positiveNumber"
        },
        "loadName": {
          "description": "Generated unique name of container",
          "type": "string",
          "pattern": "^[a-z0-9._]+$"
        },
        "isMagneticModuleCompatible": {
          "description": "Flag marking whether a labware is compatible by default with the Magnetic Module",
          "type": "boolean"
        },
        "magneticModuleEngageHeight": {
          "description": "Distance to move magnetic module magnets to engage",
          "$ref": "#/definitions/positiveNumber"
        }
      }
    },
    "ordering": {
      "type": "array",
      "description": "Generated array that keeps track of how wells should be ordered in a labware",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "cornerOffsetFromSlot": {
      "type": "object",
      "additionalProperties": false,
      "description": "Distance from left-front-bottom corner of slot to left-front-bottom corner of labware",
      "required": ["x", "y", "z"],
      "properties": {
        "x": { "type": "number" },
        "y": { "type": "number" },
        "z": { "type": "number" }
      }
    },
    "dimensions": {
      "type": "object",
      "additionalProperties": false,
      "description": "Outer dimensions of a labware",
      "required": ["overallWidth", "overallHeight", "overallLength"],
      "properties": {
        "overallWidth": {
          "$ref": "#/definitions/positiveNumber"
        },
        "overallHeight": {
          "$ref": "#/definitions/positiveNumber"
        },
        "overallLength": {
          "$ref": "#/definitions/positiveNumber"
        }
      }
    },
    "wells": {
      "type": "object",
      "description": "Unordered object of well objects with position and dimensional information",
      "patternProperties": {
        "['A' - 'Z'][*]": {
          "type": "object",
          "additionalProperties": false,
          "required": ["depth", "shape", "totalLiquidVolume", "x", "y", "z"],
          "oneOf": [
            { "required": ["width", "length"] },
            { "required": ["diameter"] }
          ],
          "not": {
            "anyOf": [
              { "required": ["diameter", "width"] },
              { "required": ["diameter", "length"] }
            ]
          },
          "properties": {
            "depth": { "$ref": "#/definitions/positiveNumber" },
            "x": {
              "description": "X location of center-top of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "y": {
              "description": "Y location of center-top of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "z": {
              "description": "Z location of center-top of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "totalLiquidVolume": {
              "description": "Total well, tube, or tip volume in microliters",
              "$ref": "#/definitions/positiveNumber"
            },
            "width": { "$ref": "#/definitions/positiveNumber" },
            "length": { "$ref": "#/definitions/positiveNumber" },
            "diameter": { "$ref": "#/definitions/positiveNumber" },
            "shape": {
              "description": "If rectangular, use length and width; otherwise use diameter",
              "type": "string",
              "enum": ["rectangular", "circular"]
            }
          }
        }
      }
    }
  }
}

=== pypi-data/pypi-mirror-45/packages/opentrons/opentrons-3.8.3-py2.py3-none-any.whl/opentrons/shared_data/definitions2/opentrons_1_trash_1.1_l.json
{
  "ordering": [["A1"]],
  "otId": "629d3b80-ecfe-11e8-b073-3da0bb8daec9",
  "deprecated": false,
  "metadata": {
    "displayCategory": "trash",
    "displayVolumeUnits": "L",
    "displayName": "Tall Fixed Trash",
    "tags": ["trash", "opentrons", "tall"]
  },
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  },
  "dimensions": {
    "overallLength": 172.86,
    "overallWidth": 165.86,
    "overallHeight": 82
  },
  "parameters": {
    "format": "trash",
    "isTiprack": false,
    "loadName": "opentrons_1_trash_1.1_l",
    "isMagneticModuleCompatible": false,
    "quirks": ["fixedTrash", "centerMultichannelOnWells"]
  },
  "wells": {
    "A1": {
      "shape": "rectangular",
      "length": 165.67,
      "width": 107.11,
      "totalLiquidVolume": 1100000,
      "depth": 77,
      "x": 82.84,
      "y": 53.56,
      "z": 5
    }
  },
  "brand": {
    "brand": "Opentrons"
  }
}
